author: SashaCtp
site: sashactp.fr
name: BallsOfSteel
main: fr.rubyz.bos.BallsOfSteel
version: 0.1
api-version: 1.13
commands:
  start:
    usage: /start
    description: Start the game
  param:
    usage: /param
    description: Open the parameters menu for the Hosts
  gametime:
    usage: /gametime <action> <int>
    description: Edit the time of the game (add/remove/set)
  debug:
    usage: /debug
    description: Only for debug purpose